-- 0001_beta_signups_baseline.sql
-- Baseline reconstruction of the beta_signups table and its RLS policies as
-- they currently exist in the live Supabase project (pavjjiiztqxbfnxkqobc).
--
-- IMPORTANT: This is a REVERSE-ENGINEERED baseline. The live schema was created
-- via the Supabase dashboard, not migrations. It is checked in here so the repo
-- is the source of truth going forward. Column types/defaults below are inferred
-- from observed behaviour (unique-email conflict code 23505 on duplicate insert,
-- anon INSERT allowed, anon SELECT denied). Verify against the dashboard before
-- treating this as authoritative, and adjust if the live definition differs.
--
-- DO NOT run this whole file against the live project as-is (the table already
-- exists). It documents current state; Stage 1's additive change is in 0002.

create table if not exists public.beta_signups (
    id          bigint generated by default as identity primary key,
    email       text        not null unique,
    created_at  timestamptz not null default now()
);

-- Row Level Security is ON. Anon can INSERT but cannot SELECT/UPDATE/DELETE,
-- so the signup list is not publicly enumerable.
alter table public.beta_signups enable row level security;

-- Anon (public, unauthenticated) may insert new signups only.
-- No USING clause (that is for SELECT/UPDATE/DELETE); WITH CHECK gates the row.
create policy "anon can insert beta signups"
    on public.beta_signups
    for insert
    to anon
    with check (true);

-- NOTE: There is deliberately NO select/update/delete policy for anon.
-- With RLS enabled and no matching policy, those operations are denied.
-- (Confirmed live: anon SELECT returns 401 / permission denied, code 42501.)
